ShowRommSys.Client.Web/Controllers/SiteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShowRommSys.Client.Web.Models;
using System.ServiceModel;
using ShowRommSys.Client.Web.Common;
using System.IO;
using Telerik.Web.Mvc;

namespace ShowRommSys.Client.Web.Controllers
{
    public class SiteController : Controller, ControlService.IMainControlCallback
    {
        private static readonly ShowRoomSysEntities DBContext = new ShowRoomSysEntities();
        //
        // GET: /Site/

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Main()
        {
            return View();
        }
        public ActionResult Menu()
        {
            var items = FunctionMenu.GetFunctionMenus(int.Parse(this.User.Identity.Name));
            return View(items);
        }
        public ActionResult UserInfo()
        {
            string user = User.Identity.Name;
            return View();
        }
        public ActionResult Welcome()
        {
            return View();
        }
        #region list
        [HttpPost]
        public ActionResult AddList(ShowItemsList itemList)
        {
            itemList.CreateTime = DateTime.Now;
            DBContext.AddToShowItemsList(itemList);
            DBContext.SaveChanges();
            if (Request.Form["resourceid"] != null)
            {
                string[] resources = Request.Form["resourceid"].TrimEnd(',').Split(',');
                var delList = DBContext.ListResources.Where(e => e.ListID == itemList.Id).ToList();
                foreach (var v in delList)
                {
                    DBContext.ListResources.DeleteObject(v);
                }
                for (int i = 0; i < resources.Length; i++)
                {
                    if (resources[i] != string.Empty)
                    {
                        ListResources ir = new ListResources { ListID = itemList.Id, ResourceID = int.Parse(resources[i]) };
                        DBContext.AddToListResources(ir);
                    }
                }
                DBContext.SaveChanges();
            }
            return RedirectToAction("IndexList");
        }
        public ActionResult IndexList()
        {
            ViewData["pageInput"] = true;
            ViewData["nextPrevious"] = true;
            ViewData["numeric"] = true;
            var list = DBContext.ShowItemsList.ToList();
            return View(list);
        }
        public ActionResult DetailsList(int ID)
        {
            var list = DBContext.ShowItemsList.FirstOrDefault(e => e.Id == ID);
            var rs = DBContext.ListResources.Where(e => e.ListID == ID).ToList();
            string results = string.Empty;
            foreach(var v in rs)
            {
                results += DBContext.Resources.FirstOrDefault(e => e.Id == v.ResourceID).Name + System.Environment.NewLine; 
            }
            ViewData["Resources"] = results;
            return View(list);
        }
        public ActionResult PlayList(int ID)
        {
            return View();
        }
        public ActionResult AddList()
        {
            List<SelectListItem> list = new List<SelectListItem>();
            var resources = DBContext.Resources.Select(e => e.Category).Distinct().ToList();
            foreach (var v in resources)
                list.Add(new SelectListItem { Text = v, Value = v });
            ViewData["ResourcesType"] = list;
            return View();
        }
        #endregion

        #region resource
        public ActionResult AddResources()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddResources(Resources rs)
        {
            if (ModelState.IsValid)
            {
                string type = Request.Form["Type"];
                string category = string.Empty;
                if (type == "2")
                    category = "链接";
                else if (type == "3")
                {
                    category = "应用程序";
                }
                else
                {
                    switch (Path.GetExtension(Request.Form["FilePath"]).ToLower().Replace(".", ""))
                    {
                        case "ppt":
                        case "pptx":
                            category = "幻灯";
                            break;
                        case "doc":
                        case "docx":
                            category = "文档";
                            break;
                        case "xls":
                        case "xlsx":
                            category = "Excel";
                            break;
                        case "avi":
                        case "wmv":
                            category = "视频";
                            break;
                        case "pdf":
                            category = "PDF";
                            break;
                        default:
                            category = "其它";
                            break;
                    }
                }
                Resources res = new Resources();
                res.Type = int.Parse(type);
                res.Approve = false;
                res.Remark = rs.Remark == null ? "" : rs.Remark;
                res.Uri = type == "1" ? Request.Form["FilePath"] : Request.Form["url"];
                if (type == "3")
                    res.Uri = Request.Form["exepath"];
                res.CreateTime = DateTime.Now;
                res.Category = category;
                res.Name = type == "1" ? Path.GetFileNameWithoutExtension(Request.Form["FilePath"]) : Request.Form["url"];
                if (type == "3")
                    res.Name = Path.GetFileNameWithoutExtension(Request.Form["exepath"]);
                DBContext.Resources.AddObject(res);
                DBContext.SaveChanges();
                return RedirectToAction("IndexResources");
            }
            return View();
        }
        public ActionResult IndexResources()
        {
            ViewData["pageInput"] = true;
            ViewData["nextPrevious"] = true;
            ViewData["numeric"] = true;
            return View(DBContext.Resources.ToList());
        }
        [HttpPost]
        public ActionResult ApproveResources(string ID)
        {
            if (ID == null)
                return null;
            List<int> result = new List<string>(ID.TrimEnd(',').Split(',')).ConvertAll(i => int.Parse(i));
            var resource = DBContext.Resources.Where(e => result.Contains(e.Id)==true);
            foreach (var r in resource)
            {
                r.Approve = true;
            }
            DBContext.SaveChanges();
            return null;
        }
        public ActionResult EditResources(int ID)
        {
            var resource = DBContext.Resources.FirstOrDefault(e => e.Id == ID);
            return View(resource);
        }
        [HttpPost]
        public ActionResult EditResources(Resources rs)
        {
            var resource = DBContext.Resources.SingleOrDefault(e => e.Id == rs.Id);
            string category = string.Empty;
            if (rs.Type == 2)
                category = "链接";
            else if (rs.Type == 1)
            {
                switch (Path.GetExtension(rs.Uri).ToLower().Replace(".", ""))
                {
                    case "ppt":
                    case "pptx":
                        category = "幻灯";
                        break;
                    case "doc":
                    case "docx":
                        category = "文档";
                        break;
                    case "xls":
                    case "xlsx":
                        category = "Excel";
                        break;
                    case "avi":
                    case "wmv":
                        category = "视频";
                        break;
                    default:
                        category = "其它";
                        break;
                }
            }
            else
                category = "应用程序";
            resource.Type = rs.Type;
            resource.Category = category;
            resource.Uri = rs.Uri;
            resource.Remark = rs.Remark;
            resource.Approve = rs.Approve;
            resource.CreateTime = rs.CreateTime;
            resource.Name = rs.Type == 2 ? rs.Uri : Path.GetFileNameWithoutExtension(rs.Uri);
            DBContext.SaveChanges();
            return RedirectToAction("IndexResources");
        }
        #endregion

        #region device
        public ActionResult AddDevice()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddDevice(Device device)
        {
            DBContext.Device.AddObject(device);
            DBContext.SaveChanges();
            return RedirectToAction("IndexDevice");
        }
        public ActionResult IndexDevice()
        {
            ViewData["pageInput"] = true;
            ViewData["nextPrevious"] = true;
            ViewData["numeric"] = true;
            var list = DBContext.Device.ToList();
            string macs = GetOnlineStatus().Replace(":","-");
            foreach (var v in list)
            {
                if (macs.IndexOf(v.MAC) >= 0)
                    v.Status = "在线";
                else
                    v.Status = "离线";
            }
            return View(list);
        }
        [NonAction]
        public string GetOnlineStatus()
        {
            try
            {
                var ctx = new InstanceContext(this);
                var svc = new ControlService.MainControlClient(ctx);
                svc.ClientCredentials.Windows.ClientCredential.UserName = System.Configuration.ConfigurationManager.AppSettings["user"];
                svc.ClientCredentials.Windows.ClientCredential.Password = System.Configuration.ConfigurationManager.AppSettings["pwd"];

ShowRommSys.Client.Web/Views/Site/AddItems.cshtml
@{
    Layout = "~/Views/Shared/MasterPage.cshtml";
}
@model ShowRommSys.Client.Web.Models.Items
<script type="text/javascript">
    var itemcount = 0;
    function GetResources() {
        var defaultOP = "<option value='0'>-资源-</option>";
        $("#ddl_Resource").empty();
        $("#ddl_Resource").append(defaultOP);
        if ($("#ddl_ResourceType").val() == "") {
            return;
        }
        var url = "/Site/GetResources/" + $("#ddl_ResourceType").val() + "/";
        $.getJSON(url, function (data) {
            $.each(data, function (i, item) {
                $("<option>" + item["Name"] + "</option>")
                .val(item["Id"])
                .appendTo($("#ddl_Resource"));
            });
        });
    }
    function AddResource() {
        if ($("#ddl_Resource").val() == "0") {
            alert("请先选择资源");
            return;
        }
        if ($("#ddl_Devices").val() == "") {
            alert("请先选择设备");
            return;
        } $("#ddl_Devices").find("option:selected").text()
        InsertToDiv($("#ddl_Resource").find("option:selected").text(), $("#ddl_Devices").find("option:selected").text(), $("#ddl_Resource").val(), $("#ddl_Devices").val());
    }
    function InsertToDiv(resource, device, rid, did) {
        var count = $("#listResource").children("p").length;
        var id = "presource" + (itemcount + 1);
        var item = "<p id='" + id + "'> " + (itemcount + 1) + "、" + resource + "（" + device + "）&nbsp;<a href='javascript:RemoveResource(\"" + id + "\");'>[移除]</a><input type='hidden' name='resourceid' value='" + rid + "'/><input type='hidden' name='diveceid' value='" + did + "'/></p>";
        $("#listResource").append(item);
        itemcount++;
    }
    function RemoveResource(id) {
        $("#" + id + "").remove();
    }
</script>
<div class="box corner-top">
    @using (Html.BeginForm())
    {
        <div class="form">
            <p><label class="field">所属展项：</label>@Html.DropDownList("ListId", (List<SelectListItem>)ViewData["ShowLists"], "-选择-", new { @class = "small" })<span class="explain">创建后不可修改</span></p>
            <p><label class="field">方案名称：</label><input name="Name" id="Name" type="text" class="text" size="50" /></p>
            <p><label class="field">备注：</label><textarea name="Remark" id="Remark" class="text full" rows="5"></textarea></p>
            <div class="hr">
                <p><label class="field">播放资源：</label>
                    @Html.DropDownList("ddl_ResourceType", (List<SelectListItem>)ViewData["ResourcesType"], "-类型-", new { onchange = "GetResources()", @class = "small" })
                    &nbsp;<select name="ddl_Resource" id="ddl_Resource" class="small"><option value="0">-资源-</option></select>
                    &nbsp;@Html.DropDownList("ddl_Devices", (List<SelectListItem>)ViewData["Devices"], "-设备-", new { @class = "small" })
                    &nbsp;<a id="btnAdd" href="javascript:AddResource();" class="btn-69">添加</a></p>
                <div id="listResource"></div>
                <p class="explain">注：可选资源为展项包含资源，无法使用其他资源</p>
            </div>
            <p><button type="submit">提交</button></p>
        </div>
    }
</div>

ShowRommSys.Client.Web/Views/Site/AddList.cshtml
@{
    Layout = "~/Views/Shared/MasterPage.cshtml";
}
@model ShowRommSys.Client.Web.Models.ShowItemsList
<script type="text/javascript">
    var itemcount = 0;
    function GetResources() {
        var defaultOP = "<option value='0'>-资源-</option>";
        $("#ddl_Resource").empty();
        $("#ddl_Resource").append(defaultOP);
        if ($("#ddl_ResourceType").val() == "") {
            return;
        }
        var url = "/Site/GetResources/" + $("#ddl_ResourceType").val() + "/";
        $.getJSON(url, function (data) {
            $.each(data, function (i, item) {
                $("<option>" + item["Name"] + "</option>")
    .val(item["Id"])
    .appendTo($("#ddl_Resource"));
            });
        });
    }
    function AddResource() {
        if ($("#ddl_Resource").val() == "0") {
            alert("请先选择资源");
            return;
        }
        InsertToDiv($("#ddl_Resource").find("option:selected").text(), $("#ddl_Resource").val());
    }
    function InsertToDiv(resource, rid) {
        var count = $("#listResource").children("p").length;
        var id = "presource" + (itemcount + 1);
        var item = "<p id='" + id + "'> " + resource + "&nbsp;<a href='javascript:RemoveResource(\"" + id + "\");'>[移除]</a><input type='hidden' name='resourceid' value='" + rid + "'/></p>";
        $("#listResource").append(item);
        itemcount++;
    }
    function RemoveResource(id) {
        $("#" + id + "").remove();
    }
</script>
<div class="box corner-top">
    @using (Html.BeginForm())
    {
        <div class="form">
            <p><label class="field">编号：</label><input name="Code" id="Code" type="text" class="text" size="20" /><span class="explain">创建后不能修改</span></p>
            <p><label class="field">名称：</label><input name="Name" id="Name" type="text" class="text" size="50" /></p>
            <p><label class="field">内容描述：</label><textarea name="Description" id="Description" class="text full" rows="5"></textarea></p>
            <p><label class="field">创建方法：</label><textarea name="CreateMethod" id="CreateMethod" class="text full" rows="5"></textarea></p>
            <p><label class="field">包含资源：</label>
                @Html.DropDownList("ddl_ResourceType", (List<SelectListItem>)ViewData["ResourcesType"], "-类型-", new { onchange = "GetResources()", @class = "small" })
                &nbsp;<select name="ddl_Resource" id="ddl_Resource" class="small"><option value="0">-资源-</option></select>&nbsp;<a id="btnAdd" href="javascript:AddResource();" class="btn-69">添加</a></p>
            <div id="listResource"></div>
            <p><button type="submit">提交</button></p>
        </div>
    }
</div>

ShowRommSys.Client.Web/Views/Site/AddNatures.cshtml
@{
    ViewBag.Title = "AddNetures";
    Layout = "~/Views/Shared/MasterPage.cshtml";
}
@model ShowRommSys.Client.Web.Models.Natures
<div class="box corner-top">
    @using (Html.BeginForm())
    {
        <div class="form">
            <p><label class="field">预约日期：</label><input name="Date" id="Date" type="text" class="text readonly" size="20" value="@ViewData["date"]" readonly="readonly" /><span class="explain"><a href="/site/calendar/">[重新选择]</a></span></p>
            <p><label class="field">预约时间：</label>
            @{
            ShowRommSys.Client.Web.Models.ShowRoomSysEntities DBContext = new ShowRommSys.Client.Web.Models.ShowRoomSysEntities();
            List<int> result = new List<string>(ViewData["date"].ToString().Split('-')).ConvertAll(i => int.Parse(i));
            int year = result[0];
            int mon = result[1];
            int day = result[2];
            int[] time = { 9, 10, 11, 14, 15, 16 };
            var list = DBContext.Natures.Where(e => e.Date.Year == year && e.Date.Month == mon && e.Date.Day == day);
            foreach (int i in time)
            {
                string str = "";
                if (list.Where(e => e.Time == i).ToList().Count > 0)
                {
                    str = "disabled='disabled'";
                }
                    <label class='checkbox'><input type='radio' name='time' value='@i.ToString()' @str />@i.ToString().PadLeft(2, '0'):00</label>;
            }
            }
            </p>
            <p><label class="field">客户名称：</label><input name="Custmor" id="Custmor" type="text" class="text" size="70" /></p>
            <p><label class="field">参观人数：</label><input name="CustmorCount" id="CustmorCount" type="text" class="text" size="10" maxlength="3" /></p>
            <p><label class="field">参观人员级别：</label><label class="checkbox"><input type="radio" name="CustmorLevel" id="CustmorLevel" value="5" />一号首长</label><label class="checkbox"><input type="radio" name="CustmorLevel" id="CustmorLevel" value="4" />副领导</label><label class="checkbox"><input type="radio" name="CustmorLevel" id="CustmorLevel" value="3" />部门领导</label><label class="checkbox"><input type="radio" name="CustmorLevel" id="CustmorLevel" value="2" />相关主管</label><label class="checkbox"><input type="radio" name="CustmorLevel" id="CustmorLevel" value="1" />其他</label></p>
            <p><label class="field">联系人姓名：</label><input name="Contact" id="Contact" type="text" class="text" size="20" /></p>
            <p><label class="field">联系人电话：</label><input name="Tel" id="Tel" type="text" class="text" size="20" maxlength="11" /></p>
            <p><label class="field">陪同人员：</label><input name="Escort" id="Escort" type="text" class="text" size="20" /></p>
            <p><label class="field">关注项目：</label><textarea name="Follow" id="Follow" class="text full" rows="5"></textarea></p>
            <p><label class="field">备注：</label><textarea name="Remark" id="Remark" class="text full" rows="5"></textarea></p>
            <p><button type="submit">提交</button>&nbsp;<a id="btnReturn" href="/site/calendar/" class="btn-69">返回</a></p>
        </div>
    }
</div>

ShowRommSys.Client.Web/Views/Site/AddPlayItems.cshtml
@{
    ViewBag.Title = "AddPlayItems";
    Layout = "~/Views/Shared/MasterPage.cshtml";
}
@model ShowRommSys.Client.Web.Models.Items
<script type="text/javascript">
    var itemcount = 0;
    function GetResources() {
        var defaultOP = "<option value='0'>-资源-</option>";
        $("#ddl_Resource").empty();
        $("#ddl_Resource").append(defaultOP);
        if ($("#ddl_ResourceType").val() == "") {
            return;
        }
        var url = "/Site/GetResources/" + $("#ddl_ResourceType").val() + "/";
        $.getJSON(url, function (data) {
            $.each(data, function (i, item) {
                $("<option>" + item["Name"] + "</option>")
                .val(item["Id"])
                .appendTo($("#ddl_Resource"));
            });
        });
    }
    function AddResource() {
        if ($("#ddl_Resource").val() == "0") {
            alert("请先选择资源");
            return;
        }
        if ($("#ddl_Devices").val() == "") {
            alert("请先选择设备");
            return;
        } $("#ddl_Devices").find("option:selected").text()
        InsertToDiv($("#ddl_Resource").find("option:selected").text(), $("#ddl_Devices").find("option:selected").text(), $("#ddl_Resource").val(), $("#ddl_Devices").val());
    }
    function InsertToDiv(resource, device, rid, did) {
        var count = $("#listResource").children("p").length;
        var id = "presource" + (itemcount + 1);
        var item = "<p id='" + id + "'> " + (itemcount + 1) + "、" + resource + "（" + device + "）&nbsp;<a href='javascript:RemoveResource(\"" + id + "\");'>[移除]</a><input type='hidden' name='resourceid' value='" + rid + "'/><input type='hidden' name='diveceid' value='" + did + "'/></p>";
        $("#listResource").append(item);
        itemcount++;
    }
    function RemoveResource(id) {
        $("#" + id + "").remove();
    }
</script>
<div class="box corner-top">
    @using (Html.BeginForm("AddItems","Site"))
    {
	
        <div class="form">
            <p>
                <label class="field">
                    展项名称：</label><input type="hidden" value="@Model.Remark" id="Remark" name="Remark"/><input type="hidden" value="@Model.Name" id="Name" name="Name"/><input type="hidden" value="@Model.Id" id="Id" name="Id"/> @Model.Name</p>
            <div class="hr">
                <p>
                    <label class="field">
                        播放名称：</label><input name="PlayName" id="PlayName" type="text" class="text" size="30" /></p>
                <p>
                    <label class="field">
                        播放资源：</label>
                    @Html.DropDownList("ddl_ResourceType", (List<SelectListItem>)ViewData["ResourcesType"], "--类型--", new { onchange = "GetResources()", @class = "small" })
                    &nbsp;<select name="ddl_Resource" id="ddl_Resource" class="small">
                        <option value="0">-资源-</option>
                    </select>&nbsp;
                    @Html.DropDownList("ddl_Devices", (List<SelectListItem>)ViewData["Devices"], "--设备--", new {@class = "small" })
                    &nbsp; <a id="btnAdd" href="javascript:AddResource();" class="btn-69">添加</a></p>
                <div id="listResource">
                    
                </div>
            </div>
            <p>
                <input id="btnSub" type="submit" value="确   定" class="btn-69"/></p>
        </div>

    }
</div>


ShowRommSys.Client.Web/Views/Site/AddResources.cshtml
@{
    ViewBag.Title = "资源添加";
    Layout = "~/Views/Shared/MasterPage.cshtml";
}
@model ShowRommSys.Client.Web.Models.Resources
<link href="../../Content/uploadify.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" language="javascript" src="../../Scripts/jquery.uploadify.v2.1.4.js"></script>
<script src="../../Scripts/swfobject.js" type="text/javascript"></script>
<script type="text/javascript">
    $(function () {
        $("input[name=Type]").click(function () {
            $("p[id^=Type]").hide();
            $("#Type" + $(this).val()).show();
        });
    });
    $(function () {
        $('#videofileInput').uploadify({
            'uploader': '../../Content/uploadify.swf',
            'script': '/Site/UploadFile',
            'folder': '/UploadFiles/',
            'cancelImg': '../../Images/Cancel.png',
            'sizeLimit': 1024 * 1024 * 1000, //1000M
            'multi': false,
            'onSelect': onSelect,
            'onComplete': funvideo,
            'onError': onError
        });
    });
    function onError(event, queueID, fileObj) {
        alert("文件:" + fileObj.name + "上传失败");
    }
    function onSelect(e, queueId, fileObj) {
    }
    function funvideo(event, queueID, fileObj, response, data) {
        if (response != "") {
            $("#FilePath").val(response);
        }
        else {
            alert("文件上传出错！");
        }
    };
</script>
<div class="box corner-top">
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)
        <div class="form">
            <p>
                <label class="field">资源类型：</label>
                <label class="checkbox">@Html.RadioButton("Type", 1, true) 文件</label>
                <label class="checkbox">@Html.RadioButton("Type", 2, false) URL</label>
                <label class="checkbox">@Html.RadioButton("Type", 3, false) 程序</label>
            </p>
            <div class="hr">
                <p id="Type1"><label class="field">上传文件：</label><input id="videofileInput" name="videofileInput" type="file" /><a href="javascript:$('#videofileInput').uploadifyUpload()">上传</a><input type="hidden" id="FilePath" name="FilePath" /></p>
                <p id="Type2" style="display:none;"><label class="field">URL地址：</label><input name="url" type="text" class="text" size="70" /></p>
                <p id="Type3" style="display:none;"><label class="field">程序路径：</label><input name="exepath" type="text" class="text" size="70" /></p>
                <p><label class="field">备注：</label><textarea name="Remark" class="text full" rows="5" id="Remark"></textarea></p>
            </div>
            <p><button type="submit">提交</button></p>
        </div>
    }
</div>

ShowRommSys.Client.Web/Views/Site/EditItemsPackage.cshtml
@{
    ViewBag.Title = "EditItemsPackage";
    Layout = "~/Views/Shared/MasterPage.cshtml";
}
@model ShowRommSys.Client.Web.Models.ItemsPackage
<script type="text/javascript">
    var itemcount = 0;
    function GetPlay() {
        if ($("#ddl_Items").val() == "") {
            return;
        }
        var defaultOP = "<option value='0'>-方式-</option>";
        $("#ddl_Play").empty();
        $("#ddl_Play").append(defaultOP);
        var url = "/Site/GetPlay/" + $("#ddl_Items").val() + "/";
        $.getJSON(url, function (data) {
            $.each(data, function (i, item) {
                $("<option>" + item["Name"] + "</option>")
                .val(item["Id"])
                .appendTo($("#ddl_Play"));
            });
        });
    }
    function AddResource() {
        if ($("#ddl_Play").val() == "0") {
            alert("请先选择方式");
            return;
        }
        if ($("#ddl_Items").val() == "") {
            alert("请先选择展项");
            return;
        } $("#ddl_Devices").find("option:selected").text()
        InsertToDiv($("#ddl_Items").find("option:selected").text(), $("#ddl_Play").find("option:selected").text(), $("#ddl_Items").val(), $("#ddl_Play").val());
    }
    function InsertToDiv(listname, itemname, listid, itemid) {
        var count = $("#listItem").children("p").length;
        var id = "listItem" + (itemcount + 1);
        var item = "<p id='" + id + "'> " + listname + "（" + itemname + "）&nbsp;<a href='javascript:RemoveResource(\"" + id + "\");'>[移除]</a><input type='hidden' name='itemid' value='" + itemid + "'/><input type='hidden' name='listid' value='" + listid + "'/></p>";
        $("#listItem").append(item);
        itemcount++;
    }
    function RemoveResource(id) {
        $("#" + id + "").remove();
    }
    function InitPlayResource() {
        var url = '/Site/InitPackage/@Model.Id';
        $.getJSON(url, function (data) {
            $.each(data, function (i, item) {
                var results = item.split(",");
                InsertToDiv(results[0], results[1], results[2], results[3]);
            });
        });
    }
    $(function(){
        InitPlayResource();
    });
</script>
<div class="box corner-top">
    @using (Html.BeginForm())
    {
        <div class="form">
            <p><label class="field">体验包名称：</label><input name="Name" id="Name" type="text" class="text" size="50" value="@Model.Name"/></p>
            <p><label class="field">备注：</label><textarea name="Remark" id="Remark" class="text full" rows="5">@Model.Remark</textarea></p>
            <p><label class="field">包含展项：</label>@Html.DropDownList("ddl_Items", (List<SelectListItem>)ViewData["Items"], "-展项-", new { onchange = "GetPlay()", @class = "small" })
                &nbsp;<select name="ddl_Play" class="small" id="ddl_Play"><option value="0">-方式-</option></select>&nbsp;<a id="btnAdd" href="javascript:AddResource();" class="btn-69">添加</a></p>
            <div id="listItem"></div>
            <p><button type="submit">保存</button>&nbsp;<a href="@Url.Content("~/site/IndexItemsPackage")" class="btn-69">返回</a></p>
        </div>
    }
</div>

ShowRommSys.Client.Web/Views/Site/EditUser.cshtml
@{
    Layout = "~/Views/Shared/MasterPage.cshtml";
}
@model ShowRommSys.Client.Web.Models.Users
<div class="box corner-top">
    @using (Html.BeginForm())
    {
    <div class="form">
        <p><label class="field">工号：</label><input name="Number" id="Number" type="text" class="text" size="20" value="@Model.Number" autocomplete="off" /></p>
        <p><label class="field">密码：</label><input name="Password" id="Password" type="password" class="text" size="20" autocomplete="off" /><span class="explain">若不修改请留空</span></p>
        <p><label class="field">角色：</label>
            @foreach (var v in new ShowRommSys.Client.Web.Models.ShowRoomSysEntities().Roles)
            {
                if (v.Id == Model.RoleId)
                {
                <label class="checkbox"><input type="radio" name="RoleId" id="RoleId" value="@v.Id" checked="checked" />@v.Name</label>
                }
                else
                { 
                <label class="checkbox"><input type="radio" name="RoleId" id="RoleId" value="@v.Id" />@v.Name</label>
                }
            }
        <div class="hr">
            <p><label class="field">姓名：</label><input name="Name" id="Name" type="text" class="text" size="20" value="@Model.Name" /></p>
            <p><label class="field">电话：</label><input name="Tel" id="Tel" type="text" class="text" size="20" maxlength="11"value="@Model.Tel" /></p>
            <p><label class="field">邮件：</label><input name="Email" id="Email" type="text" class="text" size="50" value="@Model.Email" /></p>
            <p><label class="field">备注：</label><textarea name="Remark" id="Remark" class="text full" rows="5">@Model.Remark</textarea></p>
        </div>
        <p><button type="submit">保存</button>&nbsp;<a href="@Url.Content("~/site/IndexUser")" class="btn-69">返回</a></p>
    </div>
    }
</div>

ShowRommSys.Client.Web/Views/Site/Welcome.cshtml
@{
    Layout = "~/Views/Shared/MasterPage.cshtml";
}
<body class="content"></body>